### ISSUE TITLE
Custom markdown styling

### ISSUE THREAD

**Issue by peturh** [dimpu/angular2-markdown#87]
I'm trying to style the markdown component. 

I'm using it in an component called `docs.component.ts` that has it's belonging `less` file. But I'm not able to make styling on the markdown component from there.

I've tried for example in `docs.component.less` where I have my <div Markdown [data]="data"></div> in my `docs.component.html`

```
markdown h3 {
 color:red;
}
```

But this doesn't "kick in".

**Comment by lukaspj** [comment]
I'm having this issue as well.
From what I can see, it is due to the fancy DOM thing that Angular does (shadow dom?). 

See the image below, the generated HTML doesn't get the _ngcontent-c2 attributes, which is automagically appended to your CSS selector.

![example code](https://user-images.githubusercontent.com/2369614/30317586-c7c6ed58-97aa-11e7-9f43-ee13e8bad788.png)

I don't know how to solve it though, one would have to either append the attribute to the generated HTML or figure out how to avoid it being appended to the generated CSS...

A quick work-around is to put your markdown-formatting in the "root css files", i.e. the style files included in .angular-cli.json (if you use the cli). As the root css files, i.e. the ones that are added to each component for the whole app, will not have the attribute appended.

**Comment by dimpu** [comment]
@peturh @lukaspj We can't apply styles like that. we need a way to send styles into the component or use id's and classes to write classes.

**Comment by dimpu** [comment]
I'm closing this issue, for now, feel free to reopen it.

**Comment by pinich** [comment]
The only simple and straightforward solution I found was to put the custom style to **styles.css** file at @lukaspj suggested.
